# Workaround for https://status.dev.azure.com/_event/179641421
trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'


jobs:
- job: nonSystemTest_jdk11
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk11:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-nonSystemTest.sh
    displayName: test-nonSystemTest.sh
- job: systemTest_jdk11
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk11:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTestNoJdkTests.sh
    displayName: test-systemTestNoJdkTests.sh
- job: systemTestOnlyJdkTests_jdk11
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk11:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTestOnlyJdkTests.sh
    displayName: test-systemTestOnlyJdkTests
- job: nonSystemTest_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk17:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-nonSystemTest.sh
    displayName: test-nonSystemTest.sh
- job: systemTestOnlyJdkTests_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk17:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTestNoJdkTests.sh
    displayName: test-systemTestNoJdkTests.sh
- job: systemTest_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk17:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTestOnlyJdkTests.sh
    displayName: test-systemTestOnlyJdkTests.sh
- job: nonSystemTest_jdk19
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk19:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-nonSystemTest.sh
    displayName: test-nonSystemTest.sh
- job: systemTest_jdk19
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk19:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTestNoJdkTests.sh
    displayName: test-systemTestNoJdkTests.sh
- job: systemTestOnlyJdkTests_jdk19
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk19:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTestOnlyJdkTests.sh
    displayName: test-systemTestOnlyJdkTests.sh
- job: misc
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdkany:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-misc.sh
    displayName: test-misc.sh
