# Workaround for https://status.dev.azure.com/_event/179641421
trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'


jobs:
- job: nonSystemTest_jdk11
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk11:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-nonSystemTest.sh
    displayName: test-nonSystemTest.sh
- job: systemTest_jdk11
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk11:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTest.sh
    displayName: test-systemTest.sh
- job: nonSystemTest_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk17:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-nonSystemTest.sh
    displayName: test-nonSystemTest.sh
- job: systemTest_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk17:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTest.sh
    displayName: test-systemTest.sh
- job: nonSystemTest_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk21:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-nonSystemTest.sh
    displayName: test-nonSystemTest.sh
- job: systemTest_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk21:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTest.sh
    displayName: test-systemTest.sh
- job: nonSystemTest_jdk23
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk23:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-nonSystemTest.sh
    displayName: test-nonSystemTest.sh
- job: systemTest_jdk23
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdk23:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-systemTest.sh
    displayName: test-systemTest.sh
- job: misc
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/randoop-ubuntu-jdkany:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./scripts/test-misc.sh
    displayName: test-misc.sh
