#!/bin/bash

# Unix shell script to run randoop.

RP_HOME=`dirname "$0"`
CP=$RP_HOME/bin:$RP_HOME/tests:$RP_HOME/lib/asm-2.2.1.jar:$RP_HOME/lib/asm-tree-2.2.1.jar:$RP_HOME/lib/jakarta-oro-2.0.8.jar:$RP_HOME/lib/junit-4.3.1.jar:$RP_HOME/lib/log4j-1.2.9.jar:$RP_HOME/systemtests/clover-ant-2.3.1/lib/clover.jar:$RP_HOME/lib/org.eclipse.core.contenttype_3.2.100.v20070319.jar:$RP_HOME/lib/org.eclipse.core.jobs_3.3.1.R33x_v20070709.jar:$RP_HOME/lib/org.eclipse.core.resources_3.3.1.R33x_v20080205.jar:$RP_HOME/lib/org.eclipse.core.runtime_3.3.100.v20070530.jar:$RP_HOME/lib/org.eclipse.equinox.common_3.3.0.v20070426.jar:$RP_HOME/lib/org.eclipse.equinox.preferences_3.2.101.R33x_v20080117.jar:$RP_HOME/lib/org.eclipse.jdt.core_3.3.3.v_793_R33x.jar:$RP_HOME/lib/org.eclipse.osgi_3.3.2.R33x_v20080105.jar:$RP_HOME/lib/org.eclipse.text_3.3.0.v20070606-0010.jar:$CLASSPATH:$INV/java:$INV/java/lib/bcel.jar

CP="$CP:$CLASSPATH"

# -Xrunhprof:cpu=samples,depth=30

java -ea -Xmx1650m -classpath "$CP" randoop.main.Main "$@"
