/*
 * PlanForLocalID.java
 * 
 * Copyright 2002 Christoph Csallner and Yannis Smaragdakis.
 */
package edu.gatech.cc.jcrasher.plans;

/**
 * PlanForLocalID
 * 
 * Plan generated by a LocalVariableDeclarationStatement. 
 * Hides identifier = reference to local variable.
 *
 * Automatic Testing: 
 * Crash java classes by passing inconvenient params
 * 
 * Christoph Csallner
 * 2002-06-12 last changed
 */
public class PlanForLocalID implements Plan {

	protected String identifier = null; //unique only inside the curernt context
	protected Class<?> type = null;  			//type of the identifier

	public Class<?> getReturnType() {return type;}
	
	/**
	 * Constructor
	 */
	public PlanForLocalID(Class<?> pType, String pID) {
		assert pType != null;
		assert pID != null;
		
		type = pType;
		identifier = pID;
	}

	
	/**
 	 * Local identifier, generated by LocalVariableDeclarationStatement.
 	 */
	public String toString(Class<?> testee) {
		return identifier;
	}

}
