#!/bin/bash
# script to call meditor with the jas engine
#
# $Id: meditor 2228 2008-11-17 22:54:43Z kredel $

LIBPATH=~/java/lib
MEDITORPATH=~/java/meditor3.0
JASPATH=.

UTILS=$LIBPATH/jython.jar:$LIBPATH/log4j.jar

JAS=$JASPATH/jas.jar:$JASPATH/jas-meditor.jar

if [[ ! -f "jas.py" ]]; then
  jar xf $JASPATH/jas-meditor.jar jas.py
fi

MEDITOR=$MEDITORPATH/meditor.jar:$MEDITORPATH/lib/jscl.jar

CLASSPATH=$UTILS:$JAS:$MEDITOR:.

mkdir -p test
#####-Dpython.home=$JASPATH/examples 
java -classpath $CLASSPATH -Duser.home=$JASPATH/examples jscl.editor.Editor
