import java.io.ByteArrayOutputStream
import javax.inject.Inject
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.ProjectLayout
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations

/** Custom class that runs the `preplace` script over the generated Javadoc. */
abstract class PreplaceTask
@Inject
constructor(private val execOperations: ExecOperations, layout: ProjectLayout) : DefaultTask() {

  /** The `preplace` script. */
  @get:InputFile abstract val preplaceScript: RegularFileProperty

  /**
   * The directory containing the Javadoc to postprocess. This task rewrites files in place, so the
   * directory is not declared as an input or an output.
   */
  @get:Internal abstract val apiDir: DirectoryProperty

  init {
    apiDir.convention(layout.buildDirectory.dir("docs/api"))
  }

  @TaskAction
  fun doTaskAction() {
    // check if perl is available
    var isPerlInstalled = true
    try {
      val myStandardOutput = ByteArrayOutputStream()
      val myErrorOutput = ByteArrayOutputStream()
      execOperations.exec {
        commandLine("perl", "-version")
        standardOutput = myStandardOutput
        errorOutput = myErrorOutput
      }
    } catch (ex: Exception) {
      logger.warn("perl is not installed; skipping Javadoc postprocessing", ex)
      isPerlInstalled = false
    }
    if (isPerlInstalled) {
      val preplace = preplaceScript.get().asFile
      val api = apiDir.get().asFile
      // Work around Javadoc bug
      execOperations.exec {
        commandLine(
          "perl",
          preplace,
          """<dt><span class="memberNameLink"><a href=".*\(\)</a></span> - Constructor for enum [a-zA-Z0-9_.]*<a href=".*</a></dt>""",
          "",
          apiDir.file("index-all.html").get().asFile,
        )
      }
      // Permit validateAPI to pass
      execOperations.exec {
        commandLine(
          "perl",
          preplace,
          """^(<meta http-equiv="Refresh" content="0;)([^ ])""",
          """\1 url=\2""",
          api,
        )
      }
      // Reduce size of diffs (when it's copied over to gh-pages branch which is under
      // version control).  Note that build/docs/api/ is the same as src/docs/api/.
      execOperations.exec {
        commandLine(
          "perl",
          preplace,
          """^<!-- Generated by javadoc \(.* -->$""",
          "",
          api,
        )
      }
      execOperations.exec {
        commandLine(
          "perl",
          preplace,
          """^<meta name="date" content="[-0-9]+">$""",
          "",
          api,
        )
      }
    }
  }
}
