/*
 * Copyright 2002,2004 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.commons.jelly.tags.ojb;

import org.apache.commons.jelly.tags.core.CoreTagLibrary;

/** Describes the Taglib. This class could be generated by XDoclet
  *
  * @author <a href="mailto:jstrachan@apache.org">James Strachan</a>
  * @version $Revision: 1.5 $
  */

public class OjbTagLibrary extends CoreTagLibrary {

    public OjbTagLibrary() {
        registerTag("broker", BrokerTag.class);
        registerTag("store", StoreTag.class);
        //registerTag("delete", DeleteTag.class);
        //registerTag("query", QueryTag.class);
        //registerTag("transaction", TransactionTag.class);
    }

}
