# Create a Docker image to compute Randoop coverage for the Defects4J,
# Toradocu, or Pascali test suites.

# "ubuntu" is the latest LTS release.  "ubuntu:rolling" is the latest release,
# but it might lag behind; as of 2024-11-16, it was still 24.04 rather than 24.10.
FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  apt-utils

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  openjdk-17-jdk

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  curl \
  git \
  gradle \
  jq \
  maven \
  python3-requests \
  xvfb

# https://github.com/svenkreiss/html5validator says
# install with pip, but it must be installed with pipx.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  pipx \
&& pipx install html5validator \
&& pipx ensurepath \
&& chmod og+rx /root
# Equivalently: export PATH="$PATH:/root/.local/bin"
ENV PATH "$PATH:/root/.local/bin"

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  perl \
  wget

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  ant \
  gcc \
  make \
  maven \
  mercurial \
  subversion \
  unzip

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  cpanminus \
&& wget https://raw.githubusercontent.com/rjust/defects4j/master/cpanfile \
&& cpanm -n --installdeps .
# Disabled tests above with "-n" because of https://rt.cpan.org/Public/Bug/Display.html?id=156367 .

RUN export DEBIAN_FRONTEND=noninteractive \
&& export TZ=America/Los_Angeles

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
