# Create a Docker image that is ready to run the main Randoop tests,
# using JDK 7.

FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN apt-get -qqy update \
&& apt-get -qqy install \
  software-properties-common \
&& add-apt-repository ppa:openjdk-r/ppa \
&& apt-get -qqy update \
&& apt-get -qqy install \
  git \
  gradle \
  openjdk-7-jdk \
  xvfb \
&& apt-get -qqy remove openjdk-8-jre-headless:amd64 \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# environment variable for X11
ENV DISPLAY :99

# Install Xvfb init script
ADD xvfb_init /etc/init.d/xvfb
RUN chmod a+x /etc/init.d/xvfb
ADD xvfb-daemon-run /usr/bin/xvfb-daemon-run
RUN chmod a+x /usr/bin/xvfb-daemon-run
