# Create a Docker image to compute Randoop coverage for the Defects4J,
# Toradocu, or Pascali test suites.

FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  openjdk-8-jdk \
&& update-java-alternatives --set java-1.8.0-openjdk-amd64

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  curl \
  git \
  gradle \
  jq \
  python3-requests \
  xvfb \
&& apt-get -qqy update \
&& apt-get -qqy install \
  python3-pip \
&& pip3 install html5validator

# Ubuntu 18.04 has Maven 3.6.0, but 3.6.1 apparently has better retry
# behavior to work around network problems.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy install wget \
&& VER=3.6.3 \
&& mkdir -p $HOME/bin/install \
&& cd $HOME/bin/install \
&& wget http://apache.mirrors.pair.com/maven/maven-3/${VER}/binaries/apache-maven-${VER}-bin.tar.gz \
&& tar xzf apache-maven-${VER}-bin.tar.gz \
&& (cd /usr/local/bin && ln -sf $HOME/bin/install/apache-maven-${VER}/bin/* .) \
&& hash -r

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  perl \
  wget

# certs lines are temporary, from https://stackoverflow.com/a/50103533/173852 .
RUN /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts \
&& /var/lib/dpkg/info/ca-certificates-java.postinst configure

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  ant \
  gcc \
  make \
  maven \
  mercurial \
  subversion \
  unzip

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  cpanminus \
&& wget https://raw.githubusercontent.com/rjust/defects4j/master/cpanfile \
&& cpanm --installdeps .

RUN export DEBIAN_FRONTEND=noninteractive \
&& pip3 install subprocess32

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy install \
  python-pip \
&& pip install subprocess32

RUN export DEBIAN_FRONTEND=noninteractive \
&& export TZ=America/Los_Angeles

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
