# Create a Docker image that is ready to run the full Randoop tests.
# It's used primarily for running miscellaneous tests such as the manual,
# Javadoc, and running the Checker Framework.

FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  curl \
  git \
  gradle \
  python3-requests \
  xvfb \
&& apt-get -qqy update \
&& apt-get -qqy install \
  python3-pip \
&& pip3 install html5validator

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  openjdk-8-jdk \
&& update-java-alternatives --set java-1.8.0-openjdk-amd64

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  perl \
  wget

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \

# certs lines are temporary, from https://stackoverflow.com/a/50103533/173852 .
RUN export DEBIAN_FRONTEND=noninteractive \
&& /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts \
&& /var/lib/dpkg/info/ca-certificates-java.postinst configure
