#!/bin/sh

# This file will be used as .git/hooks/pre-commit .
# However, it should be edited as scripts/git-hook-pre-commit .

# Fail if any command fails
set -e

# The manual is rarely changed, and Travis validates the manual anyway.
./gradlew verifyGoogleJavaFormat assemble compileTestJava
