#!/bin/sh

# This file will be used as .git/hooks/pre-commit .
# However, it should be edited as scripts/git-hook-pre-commit .

# Fail if any command fails
set -e

# Be certain that:
#   the changed code is formatted correctly
#   all files have proper javadoc comments
#   all code compiles
./gradlew checkFormat checkstyle compileAll
